In [1]:
# Ej 1

import pandas as pd

url = 'https://raw.githubusercontent.com/fpineyro/homework-0/master/heart_disease.csv'
d_hd = pd.read_csv(url)

display(d_hd.head())

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
0,63,male,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0,0,no
1,67,male,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,1,yes
2,67,male,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1,1,yes
3,37,male,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0,0,no
4,41,female,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0,0,no

In [2]:

# Ej 2

display(d_hd.head(5))
display(d_hd.tail(5))

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
0,63,male,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0,0,no
1,67,male,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,1,yes
2,67,male,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1,1,yes
3,37,male,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0,0,no
4,41,female,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0,0,no

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
298,45,male,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1,0,yes
299,68,male,4,144,193,1,0,141,0,3.4,2,2.0,7.0,2,0,yes
300,57,male,4,130,131,0,0,115,1,1.2,2,1.0,7.0,3,1,yes
301,57,female,2,130,236,0,2,174,0,0.0,2,1.0,3.0,1,0,yes
302,38,male,3,138,175,0,0,173,0,0.0,1,NaN,3.0,0,0,no

In [5]:
# Ej 3

seleccion = d_hd[['age', 'has_heart_disease']]
display(seleccion)

     age has_heart_disease
0     63                no
1     67               yes
2     67               yes
3     37                no
4     41                no
..   ...               ...
298   45               yes
299   68               yes
300   57               yes
301   57               yes
302   38                no

[303 rows x 2 columns]

In [8]:
# Ej 4

filtro = d_hd[d_hd['serum_cholestoral'] > 250]
display(filtro)

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
1,67,male,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,1,yes
6,62,female,4,140,268,0,2,160,0,3.6,3,2.0,3.0,3,0,yes
7,57,female,4,120,354,0,0,163,1,0.6,1,0.0,3.0,0,1,no
8,63,male,4,130,254,0,2,147,0,1.4,2,1.0,7.0,2,0,yes
11,56,female,2,140,294,0,2,153,0,1.3,2,0.0,3.0,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,57,male,4,110,335,0,0,143,1,3.0,2,1.0,7.0,2,1,yes
281,47,male,3,130,253,0,0,179,0,0.0,1,0.0,3.0,0,0,no
285,58,male,4,114,318,0,1,140,0,4.4,3,3.0,6.0,4,0,yes
291,55,female,2,132,342,0,0,166,0,1.2,1,0.0,3.0,0,0,no
298,45,male,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1,0,yes

In [10]:
# Ej 5

nulos = d_hd.isnull().sum()
display(nulos)

age                       0
gender                    0
chest_pain                0
resting_blood_pressure    0
serum_cholestoral         0
fasting_blood_sugar       0
resting_electro           0
max_heart_rate            0
exer_angina               0
oldpeak                   0
slope                     0
num_vessels_flour         4
thal                      2
heart_disease_severity    0
exter_angina              0
has_heart_disease         0
dtype: int64

In [14]:
# Ej 6

d_hd['thal'] = d_hd['thal'].fillna(999)

display(d_hd[d_hd['thal'] == 999])

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
87,53,female,3,128,216,0,2,115,0,0.0,1,0.0,999.0,0,0,no
266,52,male,4,128,204,1,0,156,1,1.0,2,0.0,999.0,2,1,yes

In [17]:
# Ej 7

filtro_edad_colesterol = d_hd[(d_hd['age'] > 60) & (d_hd['serum_cholestoral'] > 250)]
display(filtro_edad_colesterol.head(10))

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
1,67,male,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,1,yes
6,62,female,4,140,268,0,2,160,0,3.6,3,2.0,3.0,3,0,yes
8,63,male,4,130,254,0,2,147,0,1.4,2,1.0,7.0,2,0,yes
32,64,male,3,140,335,0,0,158,0,0.0,1,0.0,3.0,1,0,yes
42,71,female,2,160,302,0,0,162,0,0.4,1,2.0,3.0,0,0,no
44,61,female,4,130,330,0,2,169,0,0.0,1,0.0,3.0,1,0,yes
48,65,female,3,140,417,1,2,157,0,0.8,1,1.0,3.0,0,0,no
70,65,female,3,155,269,0,0,148,0,0.8,1,0.0,3.0,0,0,no
71,67,male,4,125,254,1,0,163,0,0.2,2,2.0,7.0,3,0,yes
72,62,male,4,120,267,0,0,99,1,1.8,2,2.0,7.0,1,1,yes

In [19]:
# Ej 8

slope_modificada = d_hd['slope'].replace({1: 'ascendente', 2: 'descendente'})
display(slope_modificada)

0                3
1      descendente
2      descendente
3                3
4       ascendente
          ...
298    descendente
299    descendente
300    descendente
301    descendente
302     ascendente
Name: slope, Length: 303, dtype: object

In [22]:
# Ej 9

d_hd['is_healthy'] = (d_hd['heart_disease_severity'] == 0)
display(d_hd.head(22))

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease,is_healthy
0,63,male,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0,0,no,True
1,67,male,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,1,yes,False
2,67,male,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1,1,yes,False
3,37,male,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0,0,no,True
4,41,female,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0,0,no,True
5,56,male,2,120,236,0,0,178,0,0.8,1,0.0,3.0,0,0,no,True
6,62,female,4,140,268,0,2,160,0,3.6,3,2.0,3.0,3,0,yes,False
7,57,female,4,120,354,0,0,163,1,0.6,1,0.0,3.0,0,1,no,True
8,63,male,4,130,254,0,2,147,0,1.4,2,1.0,7.0,2,0,yes,False
9,53,male,4,140,203,1,2,155,1,3.1,3,0.0,7.0,1,1,yes,False
10,57,male,4,140,192,0,0,148,0,0.4,2,0.0,6.0,0,0,no,True
11,56,female,2,140,294,0,2,153,0,1.3,2,0.0,3.0,0,0,no,True
12,56,male,3,130,256,1,2,142,1,0.6,2,1.0,6.0,2,1,yes,False
13,44,male,2,120,263,0,0,173,0,0.0,1,0.0,7.0,0,0,no,True
14,52,male,3,172,199,1,0,162,0,0.5,1,0.0,7.0,0,0,no,True
15,57,male,3,150,168,0,0,174,0,1.6,1,0.0,3.0,0,0,no,True
16,48,male,2,110,229,0,0,168,0,1.0,3,0.0,7.0,1,0,yes,False
17,54,male,4,140,239,0,0,160,0,1.2,1,0.0,3.0,0,0,no,True
18,48,female,3,130,275,0,0,139,0,0.2,1,0.0,3.0,0,0,no,True
19,49,male,2,130,266,0,0,171,0,0.6,1,0.0,3.0,0,0,no,True
20,64,male,1,110,211,0,2,144,1,1.8,2,0.0,3.0,0,1,no,True
21,58,female,1,150,283,1,2,162,0,1.0,1,0.0,3.0,0,0,no,True

In [24]:
# Ej 10

d_hd_clean = d_hd.copy()
d_hd_clean = d_hd_clean.dropna()

display(d_hd_clean.isnull().sum())

age                       0
gender                    0
chest_pain                0
resting_blood_pressure    0
serum_cholestoral         0
fasting_blood_sugar       0
resting_electro           0
max_heart_rate            0
exer_angina               0
oldpeak                   0
slope                     0
num_vessels_flour         0
thal                      0
heart_disease_severity    0
exter_angina              0
has_heart_disease         0
is_healthy                0
dtype: int64